### ISSUE TITLE
[bug] Webpack 4 not killing previous process

### ISSUE THREAD

**Issue by kybarg** [diegohaz/webpack-spawn-plugin#16]
Adding **force** option to **fkill** helps to solve the issue.
maybe need to add ability to pass **fkill** options via plugin?

```diff
- promise = fkill(this.pid)
+ promise = fkill(this.pid, { force: true })
```

https://github.com/diegohaz/webpack-spawn-plugin/blob/dc38a27f061df331db09cc7682a03be080b5d71b/src/index.js#L39

**Comment by diegohaz** [comment]
I think we can safely add `force: true` for now.
